-- https://programmers.co.kr/learn/courses/30/lessons/59411

SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS AS INS, ANIMAL_OUTS AS OUTS
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY DATEDIFF(INS.DATETIME, OUTS.DATETIME)
LIMIT 2